version: '3.9'
services:
  server:
    build: .
    ports:
      - "8090:8090"
    networks:
      - practice-network
    restart: on-failure
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: 123
      POSTGRES_DB: pract_15_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    networks:
      - practice-network

networks:
  practice-network: